### ISSUE TITLE
crashes in MC 1.20.2 with Fabric 0.90.4

### ISSUE THREAD

**Issue by camlostCZ** [AdvancedXRay/Auto-Clicker-Fabric#43]
I use the Mondrinth laucher, Java 17, Windows 11. No other mods (except the Fabric API) installed.

**To Reproduce**
1. Run the game.
2. Enter a world (no difference if local freshly created or a public server).
3. Pres O to enter the mod settings. 
4. "Saving the game" message appears in the game, game terminates.

**Expected behavior**
The settings dialog opens.

**Minecraft Enviorment**
 - Minecraft Version: [eg: 1.20.2]
 - Fabric 0.90.4

**Additional context**
Crash log:
[09:18:13] [main/INFO]: Loading Minecraft 1.20.2 with Fabric Loader 0.14.22
[09:18:14] [main/INFO]: Loading 54 mods:
	- autoclicker-fabric 1.20.1-1.8.0-build.25
	- fabric-api 0.90.4+1.20.2
	   |-- fabric-api-base 0.4.33+fce67b32a0
	   |-- fabric-api-lookup-api-v1 1.6.42+b1792f7da0
	   |-- fabric-biome-api-v1 13.0.14+b1792f7da0
	   |-- fabric-block-api-v1 1.0.12+73761d2ea0
	   |-- fabric-block-view-api-v2 1.0.1+73761d2ea0
	   |-- fabric-blockrenderlayer-v1 1.1.43+f4b7e424a0
	   |-- fabric-client-tags-api-v1 1.1.4+86b12645a0
	   |-- fabric-command-api-v1 1.2.37+f71b366fa0
	   |-- fabric-command-api-v2 2.2.16+b1792f7da0
	   |-- fabric-commands-v0 0.2.54+df3654b3a0
	   |-- fabric-containers-v0 0.1.74+df3654b3a0
	   |-- fabric-content-registries-v0 5.0.5+b1792f7da0
	   |-- fabric-convention-tags-v1 1.5.8+b1792f7da0
	   |-- fabric-crash-report-info-v1 0.2.20+f4b7e424a0
	   |-- fabric-data-generation-api-v1 13.1.4+b1792f7da0
	   |-- fabric-dimensions-v1 2.1.57+b1792f7da0
	   |-- fabric-entity-events-v1 1.5.26+b1792f7da0
	   |-- fabric-events-interaction-v0 0.6.10+b1792f7da0
	   |-- fabric-events-lifecycle-v0 0.2.69+df3654b3a0
	   |-- fabric-game-rule-api-v1 1.0.41+b1792f7da0
	   |-- fabric-item-api-v1 2.1.33+b1792f7da0
	   |-- fabric-item-group-api-v1 4.0.15+e3d2bf3fa0
	   |-- fabric-key-binding-api-v1 1.0.38+f4b7e424a0
	   |-- fabric-keybindings-v0 0.2.36+df3654b3a0
	   |-- fabric-lifecycle-events-v1 2.2.27+b1792f7da0
	   |-- fabric-loot-api-v2 2.1.1+3ba460fba0
	   |-- fabric-message-api-v1 6.0.2+e3d2bf3fa0
	   |-- fabric-mining-level-api-v1 2.1.55+f4b7e424a0
	   |-- fabric-model-loading-api-v1 1.0.6+b1792f7da0
	   |-- fabric-models-v0 0.4.5+9386d8a7a0
	   |-- fabric-networking-api-v1 3.0.10+b1792f7da0
	   |-- fabric-object-builder-api-v1 12.1.2+2ff98d3ba0
	   |-- fabric-particles-v1 1.1.4+f4b7e424a0
	   |-- fabric-recipe-api-v1 2.0.7+b1792f7da0
	   |-- fabric-registry-sync-v0 4.0.5+b1792f7da0
	   |-- fabric-renderer-api-v1 3.2.1+2034447ca0
	   |-- fabric-renderer-indigo 1.5.1+2034447ca0
	   |-- fabric-renderer-registries-v1 3.2.49+df3654b3a0
	   |-- fabric-rendering-data-attachment-v1 0.3.39+73761d2ea0
	   |-- fabric-rendering-fluids-v1 3.0.30+f4b7e424a0
	   |-- fabric-rendering-v0 1.1.52+df3654b3a0
	   |-- fabric-rendering-v1 3.0.11+b1792f7da0
	   |-- fabric-resource-conditions-api-v1 2.3.10+e3d2bf3fa0
	   |-- fabric-resource-loader-v0 0.11.12+b1792f7da0
	   |-- fabric-screen-api-v1 2.0.12+b1792f7da0
	   |-- fabric-screen-handler-api-v1 1.3.40+b1792f7da0
	   |-- fabric-sound-api-v1 1.0.14+f4b7e424a0
	   |-- fabric-transfer-api-v1 3.3.9+b1792f7da0
	   \-- fabric-transitive-access-wideners-v1 5.0.3+fce67b32a0
	- fabricloader 0.14.22
	- java 17
	- minecraft 1.20.2
[09:18:14] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/{COMPUTER_USERNAME}/AppData/Roaming/com.modrinth.theseus/meta/libraries/net/fabricmc/sponge-mixin/0.12.5+mixin.0.8.5/sponge-mixin-0.12.5+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[09:18:14] [main/INFO]: Compatibility level set to JAVA_16
[09:18:14] [main/INFO]: Compatibility level set to JAVA_17
[09:18:21] [Datafixer Bootstrap/INFO]: 192 Datafixer optimizations took 152 milliseconds
[09:18:23] [Render thread/INFO]: Environment: Environment[accountsHost=https://api.mojang.com, sessionHost=https://sessionserver.mojang.com, servicesHost=https://api.minecraftservices.com, name=PROD]
[09:18:24] [Render thread/INFO]: Setting user: {MINECRAFT_USERNAME}
[09:18:24] [Render thread/INFO]: Auto Clicker Initialised
[09:18:25] [Render thread/INFO]: [Indigo] Registering Indigo renderer!
[09:18:25] [Render thread/INFO]: Backend library: LWJGL version 3.3.2-snapshot
[09:18:26] [Render thread/INFO]: Reloading ResourceManager: vanilla, fabric (autoclicker-fabric, fabric-api, fabric-api-base, fabric-api-lookup-api-v1, fabric-biome-api-v1, fabric-block-api-v1, fabric-block-view-api-v2, fabric-blockrenderlayer-v1, fabric-client-tags-api-v1, fabric-command-api-v1, fabric-command-api-v2, fabric-commands-v0, fabric-containers-v0, fabric-content-registries-v0, fabric-convention-tags-v1, fabric-crash-report-info-v1, fabric-data-generation-api-v1, fabric-dimensions-v1, fabric-entity-events-v1, fabric-events-interaction-v0, fabric-events-lifecycle-v0, fabric-game-rule-api-v1, fabric-item-api-v1, fabric-item-group-api-v1, fabric-key-binding-api-v1, fabric-keybindings-v0, fabric-lifecycle-events-v1, fabric-loot-api-v2, fabric-message-api-v1, fabric-mining-level-api-v1, fabric-model-loading-api-v1, fabric-models-v0, fabric-networking-api-v1, fabric-object-builder-api-v1, fabric-particles-v1, fabric-recipe-api-v1, fabric-registry-sync-v0, fabric-renderer-api-v1, fabric-renderer-indigo, fabric-renderer-registries-v1, fabric-rendering-data-attachment-v1, fabric-rendering-fluids-v1, fabric-rendering-v0, fabric-rendering-v1, fabric-resource-conditions-api-v1, fabric-resource-loader-v0, fabric-screen-api-v1, fabric-screen-handler-api-v1, fabric-sound-api-v1, fabric-transfer-api-v1, fabric-transitive-access-wideners-v1, fabricloader)
[09:18:27] [Worker-Main-14/INFO]: Found unifont_all_no_pua-15.0.06.hex, loading
[09:18:28] [Render thread/WARN]: Missing sound for event: minecraft:item.goat_horn.play
[09:18:28] [Render thread/WARN]: Missing sound for event: minecraft:entity.goat.screaming.horn_break
[09:18:29] [Render thread/INFO]: OpenAL initialized on device OpenAL Soft on Reproduktory (3 - FiiO BTA30 PRO)
[09:18:29] [Render thread/INFO]: Sound engine started
[09:18:29] [Render thread/INFO]: Created: 1024x512x4 minecraft:textures/atlas/blocks.png-atlas
[09:18:29] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/signs.png-atlas
[09:18:29] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/banner_patterns.png-atlas
[09:18:29] [Render thread/INFO]: Created: 512x512x4 minecraft:textures/atlas/shield_patterns.png-atlas
[09:18:29] [Render thread/INFO]: Created: 1024x1024x4 minecraft:textures/atlas/armor_trims.png-atlas
[09:18:29] [Render thread/INFO]: Created: 256x256x4 minecraft:textures/atlas/chest.png-atlas
[09:18:29] [Render thread/INFO]: Created: 128x64x4 minecraft:textures/atlas/decorated_pot.png-atlas
[09:18:29] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/shulker_boxes.png-atlas
[09:18:29] [Render thread/INFO]: Created: 512x256x4 minecraft:textures/atlas/beds.png-atlas
[09:18:29] [Render thread/WARN]: Shader rendertype_entity_translucent_emissive could not find sampler named Sampler2 in the specified shader program.
[09:18:29] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/particles.png-atlas
[09:18:29] [Render thread/INFO]: Created: 256x256x0 minecraft:textures/atlas/paintings.png-atlas
[09:18:29] [Render thread/INFO]: Created: 128x128x0 minecraft:textures/atlas/mob_effects.png-atlas
[09:18:29] [Render thread/INFO]: Created: 1024x512x0 minecraft:textures/atlas/gui.png-atlas
[09:19:00] [Render thread/INFO]: Loaded 7 recipes
[09:19:00] [Render thread/INFO]: Loaded 1271 advancements
[09:19:05] [Render thread/INFO]: Applied 0 biome modifications to 0 of 64 new biomes in 1.562 ms
[09:19:05] [Server thread/INFO]: Starting integrated minecraft server version 1.20.2
[09:19:05] [Server thread/INFO]: Generating keypair
[09:19:09] [Server thread/INFO]: Preparing start region for dimension minecraft:overworld
[09:19:10] [Render thread/INFO]: Preparing spawn area: 0%
[09:19:10] [Render thread/INFO]: Preparing spawn area: 0%
[09:19:10] [Render thread/INFO]: Preparing spawn area: 0%
[09:19:10] [Render thread/INFO]: Preparing spawn area: 0%
[09:19:11] [Render thread/INFO]: Preparing spawn area: 1%
[09:19:11] [Render thread/INFO]: Preparing spawn area: 2%
[09:19:12] [Render thread/INFO]: Preparing spawn area: 3%
[09:19:12] [Render thread/INFO]: Preparing spawn area: 5%
[09:19:13] [Render thread/INFO]: Preparing spawn area: 7%
[09:19:13] [Render thread/INFO]: Preparing spawn area: 10%
[09:19:14] [Render thread/INFO]: Preparing spawn area: 14%
[09:19:14] [Render thread/INFO]: Preparing spawn area: 16%
[09:19:15] [Render thread/INFO]: Preparing spawn area: 18%
[09:19:15] [Render thread/INFO]: Preparing spawn area: 23%
[09:19:16] [Render thread/INFO]: Preparing spawn area: 26%
[09:19:16] [Render thread/INFO]: Preparing spawn area: 30%
[09:19:17] [Render thread/INFO]: Preparing spawn area: 32%
[09:19:17] [Render thread/INFO]: Preparing spawn area: 37%
[09:19:18] [Render thread/INFO]: Preparing spawn area: 42%
[09:19:18] [Render thread/INFO]: Preparing spawn area: 44%
[09:19:19] [Render thread/INFO]: Preparing spawn area: 48%
[09:19:19] [Render thread/INFO]: Preparing spawn area: 54%
[09:19:20] [Render thread/INFO]: Preparing spawn area: 56%
[09:19:20] [Render thread/INFO]: Preparing spawn area: 61%
[09:19:21] [Render thread/INFO]: Preparing spawn area: 64%
[09:19:21] [Render thread/INFO]: Preparing spawn area: 68%
[09:19:22] [Render thread/INFO]: Preparing spawn area: 72%
[09:19:22] [Render thread/INFO]: Preparing spawn area: 76%
[09:19:23] [Render thread/INFO]: Preparing spawn area: 81%
[09:19:23] [Render thread/INFO]: Preparing spawn area: 84%
[09:19:24] [Render thread/INFO]: Preparing spawn area: 86%
[09:19:24] [Render thread/INFO]: Preparing spawn area: 92%
[09:19:25] [Render thread/INFO]: Preparing spawn area: 96%
[09:19:25] [Render thread/INFO]: Time elapsed: 16226 ms
[09:19:25] [Server thread/INFO]: Changing view distance to 12, from 10
[09:19:25] [Server thread/INFO]: Changing simulation distance to 12, from 0
[09:19:26] [Netty Server IO #1/INFO]: Negotiated common packet version 1
[09:19:26] [Netty Local Client IO #0/INFO]: Negotiated common packet version 1
[09:19:26] [Server thread/INFO]: {MINECRAFT_USERNAME}[local:E:ab6fd7ce] logged in with entity id 173 at (-227.5, 70.0, 385.5)
[09:19:27] [Server thread/INFO]: {MINECRAFT_USERNAME} joined the game
[09:19:27] [Render thread/INFO]: Loaded 2 advancements
[09:19:28] [Server thread/INFO]: Saving and pausing game...
[09:19:28] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[09:19:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[09:19:29] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[09:20:17] [Server thread/INFO]: Stopping server
[09:20:17] [Server thread/INFO]: Saving players
[09:20:17] [Server thread/INFO]: Saving worlds
[09:20:18] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:overworld
[09:20:19] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_nether
[09:20:19] [Server thread/INFO]: Saving chunks for level 'ServerLevel[New World]'/minecraft:the_end
[09:20:19] [Server thread/INFO]: ThreadedAnvilChunkStorage (New World): All chunks are saved
[09:20:19] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM-1): All chunks are saved
[09:20:19] [Server thread/INFO]: ThreadedAnvilChunkStorage (DIM1): All chunks are saved
[09:20:19] [Server thread/INFO]: ThreadedAnvilChunkStorage: All dimensions are saved
[09:20:19] [Render thread/ERROR]: Reported exception thrown!
net.minecraft.class_148: Rendering screen
	at net.minecraft.class_757.method_3192(class_757.java:955) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1275) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[1.20.2-0.14.22.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
Caused by: java.lang.NoSuchMethodError: 'void pro.mikey.autoclicker.OptionsScreen.method_25420(net.minecraft.class_332)'
	at pro.mikey.autoclicker.OptionsScreen.method_25394(OptionsScreen.java:141) ~[auto-clicker-fabric-1.20.1-1.8.0-build.25.jar:?]
	at net.minecraft.class_437.method_47413(class_437.java:110) ~[client-intermediary.jar:?]
	at net.minecraft.class_757.method_3192(class_757.java:946) ~[client-intermediary.jar:?]
	... 6 more

**Comment by MichaelHillcox** [comment]
Wrong mod version for that mc version
